# Generated by Django 4.0 on 2022-10-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='instagram_clone/profile_photos/'),
        ),
    ]
