# Generated by Django 4.0 on 2022-10-23 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_clone', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
